### ISSUE TITLE
100%又是一个只能在通义千问上用的假开源

### ISSUE THREAD

**Issue by lifeng5658** [aigc3d/motionshop#2]
100%又是一个只能在通义千问上用的假开源

**Comment by zhangwlgq** [comment]
你好，详尽的算法框架已经在我们的[主页](https://aigc3d.github.io/motionshop)上列出并给出了参考的项目或论文，可以参考实现，如果遇到问题我们也很乐意提供帮助。

另外也非常欢迎在我们的[模搭页面](https://modelscope.cn/studios/Damo_XR_Lab/motionshop/summary)上免费使用，感谢对我们项目的关注。

**Comment by 0569** [comment]
你说得对
