### ISSUE TITLE
代码是否开源？

### ISSUE THREAD

**Issue by shawnFuu** [aigc3d/motionshop#3]
不得不说这是一个杰出的工作，但是我好像并没有看见模型架构及训练等相关代码

**Comment by zhangwlgq** [comment]
你好，感谢关注我们的工作。

详尽的算法框架已经在我们的[主页](https://aigc3d.github.io/motionshop)上列出并给出了参考的项目或论文，可以参考实现。也欢迎到我们的[模搭页面](https://modelscope.cn/studios/Damo_XR_Lab/motionshop/summary)上免费使用。
